### ISSUE TITLE
无法载入chinese-roberta-wwm-ext-large的资源

### ISSUE THREAD

**Issue by galigaligo** [huahuahuage/Bert-VITS2-Speech#2]
`[INFO] - 正在加载配置文件...
[INFO] - 欢迎使用 花花 Bert-VITS2 原神/星铁语音合成API助手。
[INFO] - 程序资源正在载入中，请稍候...
Traceback (most recent call last):
  File "launch.py", line 45, in <module>
    from api.api import app as api_app
  File "E:\Bert-VITS2\Bert-VITS2-Speech-main\api\api.py", line 11, in <module>
    from .tts import tts_instance
  File "E:\Bert-VITS2\Bert-VITS2-Speech-main\api\tts.py", line 9, in <module>
    from onnx_infer.onnx_infer import infor_onnx_instance
  File "E:\Bert-VITS2\Bert-VITS2-Speech-main\onnx_infer\onnx_infer.py", line 11, in <module>
    from .text.cleaner import clean_text, cleaned_text_to_sequence
  File "E:\Bert-VITS2\Bert-VITS2-Speech-main\onnx_infer\text\cleaner.py", line 7, in <module>
    from .japanese import text_normalize as jp_text_normalize
  File "E:\Bert-VITS2\Bert-VITS2-Speech-main\onnx_infer\text\japanese.py", line 10, in <module>
    from .tokenizer import tokenizer_instance
  File "E:\Bert-VITS2\Bert-VITS2-Speech-main\onnx_infer\text\tokenizer.py", line 16, in <module>
    class BertTokenizerDict:
  File "E:\Bert-VITS2\Bert-VITS2-Speech-main\onnx_infer\text\tokenizer.py", line 22, in BertTokenizerDict
    BertTokenizer.from_pretrained(CHINESE_ONNX_LOCAL_DIR)
  File "D:\soft\miniconda\vits2\lib\site-packages\transformers\tokenization_utils_base.py", line 2028, in from_pretrained
    return cls._from_pretrained(
  File "D:\soft\miniconda\vits2\lib\site-packages\transformers\tokenization_utils_base.py", line 2242, in _from_pretrained
    added_tokens = tokenizer_file_handle.pop("added_tokens")
KeyError: 'added_tokens'`

运行程序会报这个错误，是transformers的版本问题吗？我使用的是transformers 4.36.2版本

**Comment by huahuahuage** [comment]
不要替换项目原有的json文件

**Comment by galigaligo** [comment]
😅读取中文的好了，读取英文的也报这个错。

File "E:\Bert-VITS2\Bert-VITS2-Speech\onnx_infer\text\tokenizer.py", line 32, in BertTokenizerDict
    DebertaV2TokenizerFast.from_pretrained(ENGLISH_ONNX_LOCAL_DIR)
added_tokens = tokenizer_file_handle.pop("added_tokens")
KeyError: 'added_tokens'

**Comment by huahuahuage** [comment]
错误都是一样的，处理一下就行
________________________________
发件人: XIN.ZHANG ***@***.***>
发送时间: 2023年12月27日 19:03
收件人: huahuahuage/Bert-VITS2-Speech ***@***.***>
抄送: huahuahuage ***@***.***>; Comment ***@***.***>
主题: Re: [huahuahuage/Bert-VITS2-Speech] 无法载入chinese-roberta-wwm-ext-large的资源 (Issue #2)


😅读取中文的好了，读取英文的也报这个错。

File "E:\Bert-VITS2\Bert-VITS2-Speech\onnx_infer\text\tokenizer.py", line 32, in BertTokenizerDict
DebertaV2TokenizerFast.from_pretrained(ENGLISH_ONNX_LOCAL_DIR)
added_tokens = tokenizer_file_handle.pop("added_tokens")
KeyError: 'added_tokens'
